config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  get '/survey', to: 'restaurants#survey', as: 'survey'
  post '/results', to: 'restaurants#results', as:'results'
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new

  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end

  def survey

  end

  def results
    
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :highprice, :medPrice, :lowPrice, :Sitdown, :Fastfood, :Drivethru, :Children, :Asian, :Bbq, :Cultural, :Vegetarian, :American, :Mexican, :Italian, :Chinese, :Buffet, :Leftovers, :Dessert, :Healthy, :Appetizers, :Tips, :Tvs, :Bar, :Burgers, :Unlimitedfries, :Breakfast, :Lunch, :Dinner, :Pizza, :Shakes, :Fried, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper

  def price_level(hi, med, low)
    if hi == true
      return "$$$"
    elsif med == true
      return "$$"
    elsif low == true
      return "$"
    end
  end
  
end

app/views/home/index.html.erb
<div style="text-align:center">
  <h1>Time 2 Eat!</h1>
  <p>Take this quick questionnaire and see where you should eat!</p>
  <%= button_to 'Start!', "" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetoeat!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_question.html.erb
<h2 class="question"><%=question%></h2>
<% if responses.length == 2
  columnsize = "col-md-6 col-sm-6 col-xs-6 answer"
  width = "33%"
elsif responses.length == 3
  columnsize = "col-md-4 col-sm-4 col-xs-12 answer"
  width = "25%"
end %>

<div class="responses-wrapper" id="<%= q %>">
  <% num = 0 %>
  <% responses.each do |r| %>
  <% num = num + 1 %>
  <% id = num.to_s + q %>
  <div class="<%= columnsize %> response"  id="<%= id %>" style="width:<%= width %>" onclick="manageChecks('<%= id %>','<%= q %>')">
    <%= f.label r %>
    <%= f.check_box r %>
  </div>
  <% end %>
</div>

<script>
function manageChecks(id,q) {
  var checkbox = $('#'+id).children('input[type="checkbox"]');
  $('#'+q).find('input[type=checkbox]:checked').removeAttr('checked');
  checkbox.prop('checked', !checkbox.prop('checked'));
}
</script>

app/views/restaurants/create.html.erb
<h1>Restaurant#create</h1>
<p>Find me in app/views/restaurant/create.html.erb</p>

app/views/restaurants/index.html.erb
<h1>Our Restaurants</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>

  <% @restaurants.each do |r| %>
    <tr>
      <td><%= r.name %></td>
      <td><%= link_to 'Show', restaurant_path(r) %></td>
    </tr>
  <% end %>

</table>
<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<div class="col-md-12 new-restaurant-wrapper">
  <h1>Add a new Restaurant!</h1>
  <%= form_for :restaurant, url: restaurants_path do |f| %>
    <div class="col-md-12">
      <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </p>
      <% Restaurant.attribute_names.each do |attr_name, attr_value| %>
        <% next if attr_name == "id" || attr_name == "created_at" || attr_name == "updated_at" || attr_name == "name" %>
        <p class="restaurant_attributes">
          <%= f.label attr_name %>
          <% if attr_name == "description" %>
            <%= f.text_area attr_name %>
          <% else %>
            <%= f.check_box attr_name %>
          <% end %>
        </p>
      <% end %>
      <p>
        <%= f.submit %>
      </p>
    </div>
  <% end %>
  <%= link_to 'Back', restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<% r = @restaurant%>
<h1><%= r.name%></h1>
<p class="restaurant-desc">
  <%= r.description %>
</p>
<p>
  <%= price_level(r.highprice, r.medPrice, r.lowPrice) %>
</p>

app/views/restaurants/survey.html.erb
<div class="col-md-12 col-sm-12 new-restaurant-wrapper text-center">
  <h1>Time to Eat!</h1>
  <%= form_for :restaurant, url: results_path do |f| %>
    <div class="col-md-12 col-sm-12">
      <div class="q1">
        <%= render partial: 'question', locals: { :f => f, :question => 'Are you looking for breakfast, lunch, or dinner?', :responses => ["breakfast", "lunch", "dinner"], :q => "q1"} %>
      </div>
      <div class="q2 hidden">
        <%= render partial: 'question', locals: { :f => f, :question => "What's your budget?", :responses => ["Under $10 per person", "Under $15 per person", "$15+ per person"], :q => "q2"} %>
      </div>
      <div class="q3 hidden">
        <%= render partial: 'question', locals: { :f => f, :question => 'Interested in fast food?', :responses => ["Yes", "No"], :q => "q3"} %>
      </div>
      <p class="hidden">
        <%= f.submit %>
      </p>
    </div>
  <% end %>
  <a id="gobackone">Go Back a Question...</a>
</div>

<script>
var x = 1;

$('.answer').on('click', function() {
  $('.q' +x).fadeOut().addClass('hidden');
  console.log(x + " before next");
  x = x + 1;
  $('.q' +x).fadeIn().removeClass('hidden');
  console.log(x + " after next");
  $('body').css('background-color', changeBG());
});

$('#gobackone').on('click', function() {
  console.log(x + ' before back');
  $('.q'+x).fadeOut().addClass('hidden');
  x = x - 1;
  console.log(x + ' after back');
  $('.q' + x).fadeIn().removeClass('hidden');
  $('body').css('background-color', changeBG());
})

function changeBG() {
  var bgColorArray = ['#FF5733', '#FFCA33', '#3ACD28', '#456', '#15B67E', '#1546B6', '#5715B6', '#B615B4', '#B6152D'];
  var color = bgColorArray[Math.floor(Math.random() * bgColorArray.length)];
  return color;
}
</script>